'use client';
import {Select,SelectTrigger,SelectValue,SelectContent,SelectItem} from '@/components/ui/select';
import {Switch} from '@/components/ui/switch';
import {Table,TableBody,TableRow,TableCell,TableHeader,TableHead} from '@/components/ui/table';
import {Ledger,paymentInvoices,balance} from '@/lib/ledger';
const money=(n:number)=>'Rs '+n.toLocaleString('en-PK');
export default function PaymentFields({data,form,change}:{data:Ledger;form:any;change:(k:string,v:any)=>void}){
 let invoices:ReturnType<typeof paymentInvoices>=[],rangeError='';try{invoices=paymentInvoices(data,form)}catch(e){rangeError=(e as Error).message}
 const total=invoices.reduce((a,i)=>a+balance(data,i),0),entered=Number(form.amount)||0;let remaining=entered;
 const allocation=invoices.map(i=>{const due=balance(data,i),amount=Math.max(0,Math.min(remaining,due));remaining-=amount;return {...i,dueNow:due,allocated:amount,left:due-amount}});
 return <><label className="field">Student<Select value={form.studentId||''} onValueChange={v=>change('studentId',v)}><SelectTrigger className="choice"><SelectValue placeholder="Choose a student"/></SelectTrigger><SelectContent>{data.students.filter(s=>!s.deletedAt||data.invoices.some(i=>i.studentId===s.id&&balance(data,i)>0)).map(s=><SelectItem value={s.id} key={s.id}>{s.name} · {s.roll}{s.deletedAt?' (deleted record)':''}</SelectItem>)}</SelectContent></Select></label><div className="form-grid"><label className="field">From Month<input required type="month" value={form.fromMonth||''} onChange={e=>change('fromMonth',e.target.value)}/></label><label className="field">To Month<input required type="month" min={form.fromMonth} value={form.toMonth||''} onChange={e=>change('toMonth',e.target.value)}/></label></div><label className="switch-field">Include unpaid earlier months<Switch checked={!!form.includeArrears} onCheckedChange={v=>change('includeArrears',v)}/></label>{rangeError&&<div className="error-box">{rangeError}</div>}<div className="payment-summary"><div><span>Total due</span><strong>{money(total)}</strong></div><div><span>Remaining after payment</span><strong>{money(Math.max(0,total-entered))}</strong></div></div><div className="form-grid"><label className="field">Amount received (Rs)<input required type="number" min="1" max={total||undefined} step="1" value={form.amount??''} onChange={e=>change('amount',e.target.value)}/></label><label className="field">Payment date<input required type="date" value={form.date||''} onChange={e=>change('date',e.target.value)}/></label></div><label className="field">Payment method<Select value={form.method||'Cash'} onValueChange={v=>change('method',v)}><SelectTrigger className="choice"><SelectValue/></SelectTrigger><SelectContent>{['Cash','Bank transfer','Easypaisa','JazzCash','Cheque'].map(m=><SelectItem key={m} value={m}>{m}</SelectItem>)}</SelectContent></Select></label><label className="field">Transaction / cheque reference<input value={form.reference||''} onChange={e=>change('reference',e.target.value)}/></label>{allocation.length>0?<Table><TableHeader><TableRow>{['Fee month','Due','This payment','Left'].map(h=><TableHead key={h}>{h}</TableHead>)}</TableRow></TableHeader><TableBody>{allocation.map(i=><TableRow key={i.id}><TableCell>{i.month}<small>{i.label}{i.month<form.fromMonth?' · Earlier arrears':''}</small></TableCell><TableCell>{money(i.dueNow)}</TableCell><TableCell>{money(i.allocated)}</TableCell><TableCell>{money(i.left)}</TableCell></TableRow>)}</TableBody></Table>:form.studentId&&<p className="muted">No unpaid fees in this selection. Generate fee months first or change the range.</p>}<div className="form-note">Payments clear the oldest selected dues first. Any remaining amount stays in Reminders and appears as arrears in later months. Fees are never added twice.</div></>
}
