export type Student={id:string;name:string;roll:string;className:string;guardian:string;phone:string;fee:number;discount:number;active:boolean;familyId?:string;deletedAt?:string};
export type Invoice={id:string;studentId:string;month:string;due:string;amount:number;label:string};
export type Payment={id:string;invoiceId:string;amount:number;date:string;method:string;reference:string;voided?:boolean;groupId?:string;periodFrom?:string;periodTo?:string};
export type Expense={id:string;title:string;category:string;amount:number;date:string};
export type TuitionPlan={id:string;studentId:string;month:string;fee:number;discount:number};
export type Ledger={deletedFees?:{invoice:Invoice;deletedAt:string}[];deletedReminderIds?:string[];tuitionPlans?:TuitionPlan[];students:Student[];invoices:Invoice[];payments:Payment[];expenses:Expense[];reminders:{id:string;invoiceId:string;date:string;note:string}[];audit:{id:string;date:string;action:string}[];settings:{school:string;address:string;phone:string;session:string;logoVersion?:string}};
export const today=()=>new Intl.DateTimeFormat('en-CA',{timeZone:'Asia/Karachi',year:'numeric',month:'2-digit',day:'2-digit'}).format(new Date());
export const emptyLedger=():Ledger=>({students:[],invoices:[],payments:[],expenses:[],reminders:[],audit:[],settings:{school:'My School',address:'',phone:'',session:'2026–2027'}});
export const paid=(s:Ledger,id:string)=>s.payments.filter(p=>p.invoiceId===id&&!p.voided).reduce((a,p)=>a+p.amount,0);
export const balance=(s:Ledger,i:Invoice)=>i.amount-paid(s,i.id);
export const status=(s:Ledger,i:Invoice)=>balance(s,i)<=0?'Paid':paid(s,i.id)>0?'Partial':i.due<today()?'Overdue':'Unpaid';
const text=(v:any,max=160)=>{if(typeof v!=='string'||!v.trim()||v.length>max)throw Error('Please complete all required fields.');return v.trim()};
const money=(v:any,zero=false)=>{const n=Number(v);if(!Number.isSafeInteger(n)||n<(zero?0:1)||n>1000000000)throw Error('Enter a valid amount in whole rupees.');return n};
const date=(v:any)=>{if(typeof v!=='string'||!/^\d{4}-\d{2}-\d{2}$/.test(v)||isNaN(Date.parse(v))||new Date(v).toISOString().slice(0,10)!==v)throw Error('Choose a valid date.');return v};
export function mutate(source:Ledger,action:string,p:any):Ledger{
 const s=structuredClone(source),id=crypto.randomUUID();let description='';
 if(action==='student') {const st:Student={id:p.id||id,name:text(p.name),roll:text(p.roll,40),className:text(p.className,40),guardian:text(p.guardian),phone:String(p.phone||'').slice(0,40),fee:money(p.fee,true),discount:money(p.discount||0,true),active:p.active!==false,familyId:String(p.familyId||'').trim().slice(0,80)};if(st.discount>st.fee)throw Error('Discount cannot exceed the monthly fee.');if(s.students.some(x=>x.roll===st.roll&&x.id!==st.id))throw Error('This admission number is already used.');if(p.id&&s.students.find(x=>x.id===p.id)?.deletedAt)throw Error('Restore this student before editing.');if(p.id&&!s.students.some(x=>x.id===p.id))throw Error('Student not found.');s.students=p.id?s.students.map(x=>x.id===p.id?st:x):[...s.students,st];description=`${p.id?'Updated':'Added'} student ${st.name}`;}
 else if(action==='delete_student'||action==='restore_student'){const st=s.students.find(x=>x.id===p.id);if(!st)throw Error('Student not found.');if(action==='delete_student'){if(st.deletedAt)throw Error('Student already deleted.');st.deletedAt=new Date().toISOString();st.active=false;description=`Deleted student ${st.name}; financial history preserved`;}else{if(!st.deletedAt)throw Error('Student is not deleted.');delete st.deletedAt;st.active=true;description=`Restored student ${st.name}`;}}
 else if(action==='delete_fee'){const invoice=s.invoices.find(i=>i.id===p.invoiceId);if(!invoice)throw Error('Fee not found or already deleted.');if(s.payments.some(pay=>pay.invoiceId===invoice.id))throw Error('This fee has payment history and cannot be deleted.');s.deletedFees=[...(s.deletedFees||[]),{invoice,deletedAt:new Date().toISOString()}];s.invoices=s.invoices.filter(i=>i.id!==invoice.id);s.deletedReminderIds=(s.deletedReminderIds||[]).filter(id=>id!==invoice.id);description=`Deleted fee ${invoice.label} for ${s.students.find(st=>st.id===invoice.studentId)?.name||'student'} (${invoice.month}), Rs ${invoice.amount}`;}
 else if(action==='delete_reminder'||action==='restore_reminder'){const invoice=s.invoices.find(i=>i.id===p.invoiceId);if(!invoice)throw Error('Fee reminder not found.');const ids=new Set(s.deletedReminderIds||[]);if(action==='delete_reminder')ids.add(invoice.id);else ids.delete(invoice.id);s.deletedReminderIds=[...ids];description=`${action==='delete_reminder'?'Deleted':'Restored'} reminder for ${s.students.find(st=>st.id===invoice.studentId)?.name||'student'} (${invoice.month}); unpaid balance unchanged`;}
 else if(action==='generate'){
 const months=monthRange(p.month,p.endMonth||p.month),due=date(p.due),selected=selectStudents(s,p).filter(x=>x.active);let count=0;
 selected.forEach(x=>months.forEach(month=>{if(!s.invoices.some(i=>i.studentId===x.id&&i.month===month&&i.label==='Monthly tuition')){const plan=tuitionFor(s,x,month);const day=Math.min(Number(due.slice(8)),new Date(Number(month.slice(0,4)),Number(month.slice(5)),0).getDate());s.invoices.push({id:crypto.randomUUID(),studentId:x.id,month,due:month+'-'+String(day).padStart(2,'0'),amount:plan.fee-plan.discount,label:'Monthly tuition'});count++}}));
 if(!count)throw Error('No new fees to generate. Existing invoices can be printed from Fee challans.');description=`Generated ${count} tuition invoices for ${months.join(', ')}`;
 }
 else if(action==='tuition'){
 const st=s.students.find(x=>x.id===p.studentId);if(!st||st.deletedAt)throw Error('Choose a current student.');monthRange(p.month,p.month);const fee=money(p.fee,true),discount=money(p.discount||0,true);if(discount>fee)throw Error('Discount cannot exceed tuition.');
 if(p.applyExisting){const invoice=s.invoices.find(i=>i.studentId===st.id&&i.month===p.month&&i.label==='Monthly tuition');if(invoice){if(fee-discount<paid(s,invoice.id))throw Error('New tuition is less than payments already received. Reverse the affected receipt first.');invoice.amount=fee-discount;}}
 s.tuitionPlans=[...(s.tuitionPlans||[]).filter(x=>!(x.studentId===st.id&&x.month===p.month)),{id,studentId:st.id,month:p.month,fee,discount}];description=`Set tuition for ${st.name} from ${p.month}: Rs ${fee-discount}`;
 }
 else if(action==='invoice'){if(!s.students.some(x=>x.id===p.studentId&&!x.deletedAt))throw Error('Choose a current student.');const due=date(p.due);s.invoices.push({id,studentId:p.studentId,month:due.slice(0,7),due,amount:money(p.amount),label:text(p.label)});description='Added fee charge';}
 else if(action==='payment_range'){
 const st=s.students.find(x=>x.id===p.studentId);if(!st)throw Error('Choose a student.');const amount=money(p.amount),when=date(p.date);if(!['Cash','Bank transfer','Easypaisa','JazzCash','Cheque'].includes(p.method))throw Error('Select a payment method.');const eligible=paymentInvoices(s,p),outstanding=eligible.reduce((a,i)=>a+balance(s,i),0);if(!eligible.length)throw Error('No unpaid fees in this period. Generate the fee months first.');if(amount>outstanding)throw Error('Payment exceeds the outstanding balance for this period.');let remaining=amount;for(const invoice of eligible){if(!remaining)break;const allocated=Math.min(remaining,balance(s,invoice));s.payments.push({id:crypto.randomUUID(),groupId:id,invoiceId:invoice.id,amount:allocated,date:when,method:p.method,reference:String(p.reference||'').slice(0,160),periodFrom:p.fromMonth,periodTo:p.toMonth});remaining-=allocated;}description=`Received Rs ${amount} from ${st.name} for ${p.fromMonth} to ${p.toMonth}; Rs ${outstanding-amount} remains due`;
 }
 else if(action==='payment'){const i=s.invoices.find(x=>x.id===p.invoiceId);if(!i)throw Error('Invoice not found.');const amount=money(p.amount);if(amount>balance(s,i))throw Error('Payment exceeds the outstanding balance.');if(!['Cash','Bank transfer','Easypaisa','JazzCash','Cheque'].includes(p.method))throw Error('Select a payment method.');s.payments.push({id,invoiceId:i.id,amount,date:date(p.date),method:p.method,reference:String(p.reference||'').slice(0,160)});description=`Received Rs ${amount} for ${s.students.find(x=>x.id===i.studentId)?.name}`;}
 else if(action==='void'){const pay=s.payments.find(x=>x.id===p.id);if(!pay||pay.voided)throw Error('Payment not found or already reversed.');if(pay.groupId)s.payments.filter(x=>x.groupId===pay.groupId).forEach(x=>x.voided=true);else pay.voided=true;description=`Reversed receipt ${(pay.groupId||pay.id).slice(0,8)}: ${text(p.reason)}`;}
 else if(action==='expense'){s.expenses.push({id,title:text(p.title),category:text(p.category),amount:money(p.amount),date:date(p.date)});description=`Recorded expense: ${p.title}`;}
 else if(action==='reminder'){if(!s.invoices.some(x=>x.id===p.invoiceId))throw Error('Invoice not found.');s.reminders.push({id,invoiceId:p.invoiceId,date:today(),note:text(p.note)});description='Logged a fee follow-up';}
 else if(action==='settings'){s.settings={school:text(p.school),address:String(p.address||'').slice(0,300),phone:String(p.phone||'').slice(0,40),session:text(p.session,40),logoVersion:/^[a-f0-9-]{36}$/.test(p.logoVersion||'')?p.logoVersion:''};description='Updated school settings';}
 else throw Error('Unknown action.');
 s.audit.unshift({id,date:new Date().toISOString(),action:description});return s;
}
export function demoLedger():Ledger {const s=emptyLedger();s.settings.school='Greenfield School';const month=today().slice(0,7);['Ayesha Khan','Muhammad Ali','Fatima Ahmed','Hassan Raza','Zainab Noor','Omar Farooq','Maryam Shah','Ibrahim Saeed'].forEach((name,n)=>{s.students.push({id:'s'+n,name,roll:'ST-'+(1001+n),className:'Class '+(4+n%4),guardian:['Ahmed Khan','Usman Ali','Bilal Ahmed','Raza Khan'][n%4],phone:'',fee:5000+(n%3)*500,discount:n===4?500:0,active:true});s.invoices.push({id:'i'+n,studentId:'s'+n,month,due:month+'-10',amount:s.students[n].fee-s.students[n].discount,label:'Monthly tuition'});if(n<5)s.payments.push({id:'DEMO-'+(1001+n),invoiceId:'i'+n,amount:n===4?2000:s.invoices[n].amount,date:month+'-05',method:n%2?'Bank transfer':'Cash',reference:''});});s.expenses=[{id:'e1',title:'Staff salaries',category:'Salaries',amount:12000,date:month+'-05'},{id:'e2',title:'Electricity bill',category:'Utilities',amount:3200,date:month+'-06'}];return s;}

export function monthRange(start:string,end:string):string[]{const valid=(m:string)=>/^\d{4}-(0[1-9]|1[0-2])$/.test(m);if(!valid(start)||!valid(end)||end<start)throw Error('Choose a valid month range.');const months:string[]=[];let y=Number(start.slice(0,4)),m=Number(start.slice(5));while(true){const key=String(y).padStart(4,'0')+'-'+String(m).padStart(2,'0');if(key>end)break;months.push(key);if(months.length>24)throw Error('Generate up to 24 months at a time.');if(++m>12){m=1;y++}}return months;}
export function selectStudents(s:Ledger,p:any):Student[]{if(p.scope==='All students')return s.students;if(p.scope==='Individual student'){if(!s.students.some(x=>x.id===p.studentId))throw Error('Choose a student.');return s.students.filter(x=>x.id===p.studentId)}if(p.scope==='Sibling family'){if(!p.familyId)throw Error('Choose a sibling family. Add a family ID to student records first.');return s.students.filter(x=>x.familyId===p.familyId)}if(p.scope==='Entire class'&&(!p.className||p.className==='All classes'))throw Error('Choose a class.');return s.students.filter(x=>!p.className||p.className==='All classes'||x.className===p.className)}
export function tuitionFor(s:Ledger,student:Student,month:string){return (s.tuitionPlans||[]).filter(p=>p.studentId===student.id&&p.month<=month).sort((a,b)=>b.month.localeCompare(a.month))[0]||{fee:student.fee,discount:student.discount};}

export function paymentInvoices(s:Ledger,p:{studentId:string;fromMonth:string;toMonth:string;includeArrears?:boolean}):Invoice[]{monthRange(p.fromMonth,p.toMonth);return s.invoices.filter(i=>i.studentId===p.studentId&&i.month<=p.toMonth&&(p.includeArrears||i.month>=p.fromMonth)&&balance(s,i)>0).sort((a,b)=>a.month.localeCompare(b.month)||a.due.localeCompare(b.due)||a.id.localeCompare(b.id));}
export function reminderInvoices(s:Ledger,throughMonth:string,includeDeleted=false):Invoice[]{monthRange(throughMonth,throughMonth);return s.invoices.filter(i=>i.month<=throughMonth&&balance(s,i)>0&&(includeDeleted||!s.deletedReminderIds?.includes(i.id))).sort((a,b)=>a.month.localeCompare(b.month)||a.due.localeCompare(b.due));}
